version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis